# Generated by Django 4.1.2 on 2023-03-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('storage', models.IntegerField(default=10)),
            ],
        ),
    ]
